name: Run Updatecli

on:
  workflow_dispatch: # run manually

jobs:
  updatecli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full git history for proper PR diff

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Updatecli
        run: |
          curl -sL https://github.com/updatecli/updatecli/releases/latest/download/updatecli_Linux_x86_64.tar.gz | tar xz
          sudo mv updatecli /usr/local/bin/

      - name: Check for changes
        run: git status

      - name: Configure Git
        run: |
          git config user.name "${{ secrets.USERNAME_GIT }}"
          git config user.email "${{ secrets.MAIL_GIT }}"

      - name: Create and checkout feature branch
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          BRANCH_NAME="updatecli-ami-update-$TIMESTAMP"
          git checkout -b $BRANCH_NAME
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
        id: branch

      - name: Run Updatecli
        run: |
          updatecli apply

      - name: Check if there are changes
        id: check_changes
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes detected."
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected."
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          TIMESTAMP=$(date +%Y-%m-%dT%H:%M:%S)
          git commit -m "Update AMI configuration - $TIMESTAMP"

      - name: Debug Git Branches (optional)
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git remote -v
          git branch -a
          git log --oneline --graph --all

      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: diillson/auto-pull-request@v1.0.1
        with:
          source_branch: ${{ steps.branch.outputs.branch_name }}
          destination_branch: "main"
          github_token: ${{ secrets.AMI_GITHUB }}
