name: Run Updatecli

on:
  workflow_dispatch: # run manually

jobs:
  updatecli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-southeast-2

      - name: Install Updatecli
        run: |
          curl -sL https://github.com/updatecli/updatecli/releases/latest/download/updatecli_Linux_x86_64.tar.gz | tar xz
          sudo mv updatecli /usr/local/bin/

      - name: Check for changes
        run: git status

      - name: Create and checkout feature branch
        run: |
         git config user.name "${{ secrets.USERNAME_GIT }}"
         git config user.email "${{ secrets.MAIL_GIT }}"
         BRANCH_NAME="ami-update-$(date +'%Y%m%d%H%M%S')"
         echo "Using branch name: $BRANCH_NAME"
         git checkout -b "$BRANCH_NAME"
         echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV  


      - name: Run Updatecli
        run: |
          updatecli apply --config fetch_latest_aws_ami/latest_ami.yml
      
      - name: Check if there are changes
        id: check_changes
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "No changes detected."
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            COMMIT_MESSAGE="Update AMI configuration - $(date +'%Y-%m-%d %H:%M:%S')"
            git commit -m "$COMMIT_MESSAGE"
            git push origin "$BRANCH_NAME"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: pull-request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          source_branch: "$BRANCH_NAME"
          destination_branch: "main"
          github_token: ${{ secrets.AMI_GITHUB}}
