name: Run Updatecli

on:
  workflow_dispatch: # run manually

jobs:
  updatecli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full git history for proper PR diff

      # - name: Set up AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4  # Updated to latest version
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
      #     aws-region: ap-southeast-2
        # Set up AWS OIDC credentials
      - name: Set up AWS OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::339713192253:role/updatecli
          aws-region: ap-south-1  # e.g. us-west-2
          role-session-name: GitHubActionsSession

      - name: Install Updatecli
        run: |
          curl -sL https://github.com/updatecli/updatecli/releases/latest/download/updatecli_Linux_x86_64.tar.gz | tar xz
          sudo mv updatecli /usr/local/bin/

      - name: Configure Git
        run: |
          git config user.name "${{ secrets.USERNAME_GIT }}"
          git config user.email "${{ secrets.MAIL_GIT }}"

      - name: Create and checkout feature branch
        id: branch
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          BRANCH_NAME="updatecli-ami-update-$TIMESTAMP"
          git checkout -b $BRANCH_NAME
          git push -u origin $BRANCH_NAME
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Run Updatecli
        run: |
          updatecli apply --config fetch_latest_aws_ami/latest_ami.yml

      - name: Check if there are changes
        id: check_changes
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "No changes detected."
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            COMMIT_MESSAGE="Update AMI configuration - $(date +'%Y-%m-%dT%H:%M:%S')"
            git commit -m "$COMMIT_MESSAGE"
            git push origin ${{ steps.branch.outputs.branch_name }}
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: diillson/auto-pull-request@v1.0.1
        with:
          source_branch: ${{ steps.branch.outputs.branch_name }}
          destination_branch: "main"
          github_token: ${{ secrets.AMI_GITHUB }}
